# Generated by Django 3.0.6 on 2020-05-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza_types',
            name='special_price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
