# Generated by Django 3.0.6 on 2020-05-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200508_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='pasta_quatity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='salad_quatity',
        ),
        migrations.AddField(
            model_name='cart',
            name='pasta_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cart',
            name='pasta_quantity',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cart',
            name='salad_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cart',
            name='salad_quantity',
            field=models.TextField(default=''),
        ),
    ]
