# Generated by Django 3.0.6 on 2020-05-08 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200508_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='pasta_quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='salad_quantity',
        ),
    ]
