# Generated by Django 3.0.6 on 2020-05-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200508_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='dp',
            field=models.TextField(default=''),
        ),
    ]
