# Generated by Django 3.0.6 on 2020-05-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_cart_dp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='sub_name',
            field=models.TextField(default=''),
        ),
    ]
