# Generated by Django 3.0.6 on 2020-05-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_cart_sub_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pizza_name',
            field=models.TextField(default=''),
        ),
    ]
