# Generated by Django 3.0.6 on 2020-05-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_order',
        ),
        migrations.AddField(
            model_name='order',
            name='dp',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='pasta_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='pizza_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='salad_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='sub_name',
            field=models.TextField(default=''),
        ),
    ]
